### ISSUE TITLE
How to Integrate Paytm payment Gateway in React Native Application

### ISSUE THREAD

**Issue by vinayak-dataman** [Paytm-Payments/paytm-payments-developer#11]
I am working on a React Native App where i need to integrate the paytm payment gate but I did find any documentation on It.

**Comment by rajat-mahajan** [comment]
We don't have an SDK for react native as of now but you can simple follow the steps mentioned here https://developer.paytm.com/docs/v1/payment-gateway and do the integration using the Payment API. 

Do let us know if you face any issue in the same.

**Comment by vinayak-dataman** [comment]
@rajat-mahajan I did not get solution to get checksum generate. Can you please provide a working example for it.

**Comment by vinayak-dataman** [comment]
@rajat-mahajan I want the solution for react native that run in android and ios both platform

**Comment by rajat-mahajan** [comment]
Checksum is created on server-side of merchant and not on the client ( Android/iOS) . Please use the library of checksum on your server  and and pass it to the client for calling Payment API's
