### ISSUE TITLE
paytm payment gatway   error connecting to sf

### ISSUE THREAD

**Issue by Deepaksunia1997** [Paytm-Payments/paytm-payments-developer#13]

**Comment by rajat-mahajan** [comment]
Can you please describe the steps and details regarding the issue you are facing?

**Comment by Deepaksunia1997** [comment]
Give me your mobile no.    Please

**Comment by rajat-mahajan** [comment]
Please reachout to devsupport@paytm.com with the details of your problem and your contact details. They will help in resolving the problem.
