### ISSUE TITLE
An Oops! moment While payment

### ISSUE THREAD

**Issue by ARYANJASHWAL** [Paytm-Payments/paytm-payments-developer#14]
An Oops! moment
Payment failed due to any of these reasons:

    Session expired due to inactivity
    You double-clicked on a button
    Our system encountered an obstacle

You can fix it yourself! Here's how:

    Clear cookies & temporary internet files of the browser
    Check payment status with your bank to avoid double payment
    Launch a new browser & start from the beginning
    Still unable to transact? visit us at paytm.com/care

**Comment by rajat-mahajan** [comment]
Thanks
