### ISSUE TITLE
In Android Integration and iOS integration is paramMap.put( "WEBSITE" , "WEBSTAGING"); correct it to paramMap.put( "WEBSITE" , "APPSTAGING"); 

### ISSUE THREAD

**Issue by sumit12kumar** [Paytm-Payments/paytm-payments-developer#16]
![image](https://user-images.githubusercontent.com/44435917/50561299-5c9e1a00-0d2f-11e9-95ea-c17355815136.png)

In Android Integration and iOS integration is paramMap.put( "WEBSITE" , "WEBSTAGING"); correct it to paramMap.put( "WEBSITE" , "APPSTAGING");

**Comment by rajat-mahajan** [comment]
@sumit12kumar You can use any of them. Please let me know if you are seeing any issue with WEBSTAGING
