### ISSUE TITLE
ERR_CONNECTION_REFUSED with appprod.paytm.in as callback in production mode.

### ISSUE THREAD

**Issue by bluerid** [Paytm-Payments/paytm-payments-developer#21]
Hi,I am trying to integrate PayTM in our app. However, I'm receiving this error message after each successful payment. 
USED _APPPROD_ as value of Website attribute.

```
{
   ERRURL: "https://appprod.paytm.in/theia/paytmCallback?ORDER_ID=ORDER_1547548501393"
   RESPCODE: -6
   RESPMSG: "net::ERR_CONNECTION_REFUSED"
   STATUS: "TXN_FAILURE"
}
```
Kindly offer a solution to this problem.

**Comment by rajat-mahajan** [comment]
@bluerid  Please use WEBSTAGING  
WEBSITE   | For staging environment: For staging environment: **WEBSTAGING** For production environment you need to get on-boarded.  More information here https://developer.paytm.com/docs/v1/payment-gateway
