### ISSUE TITLE
Paytm checksum mismatch.

### ISSUE THREAD

**Issue by darshanswami** [Paytm-Payments/paytm-payments-developer#26]
Hi

We are generating checksum from our server side(PHP) and send to Paytm API by iOS/Androd SDK but we are getting error response like this

{"ORDERID":"1548940249", "MID":"XXXXXXXXXX", "TXNAMOUNT":"1.00", "CURRENCY":"INR", "STATUS":"TXN_FAILURE", "RESPCODE":"330", "RESPMSG":"Paytm checksum mismatch.", "BANKTXNID":"", "CHECKSUMHASH":"oCiJdcZHnZ+EOfs165/qfh5VJNy+uw6JDXJPapzE9CGZQsHpwoxlQQNIx5OdTVAaiZY2RK1l7gPJYcf2LedE3puAq5p5Sgb1yP6tCzRi3S0="}

Can you please help me with this?

Thanks

**Comment by rajat-mahajan** [comment]
Please email devsupport@paytm.com for any tech related issues.
