### ISSUE TITLE
WEBSITE Parameter should be APPSTAGING for Android and iOS SDK.

### ISSUE THREAD

**Issue by YaMo97** [Paytm-Payments/paytm-payments-developer#9]
In the Android SDK Doc - [Description of Parameters used in Hashmap Object](https://github.com/Paytm-Payments/paytm-payments-developer/blob/master/src/pages/docs/v1/android-sdk/index.md#description-of-parameters-used-in-hashmap-object).

> **WEBSITE** String(30) Mandatory: -
For staging environment: WEBSTAGING. 
For production environment: Will be available here once your activation is complete 

Shouldn't `WEBSITE` be `APPSTAGING` for **APPs**, and  `WEBSTAGING` for **Web**,  as per the previous documentation.

**Comment by rajat-mahajan** [comment]
WEBSTAGING is the default value for all cases i.e Web and APP.  However merchant has the option to configure any other value from the portal.
